name: CommonHelpers.Maui Prerelease

on:
  workflow_dispatch:
  push:
    branches:
      - prerelease

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3


    # ****** Update version numbers ***** #

    - name: Add Release Candidate (-rc) suffix to Version Number
      run : |
        [xml]$projXml = get-content "src\CommonHelpers.Maui\CommonHelpers.Maui.csproj"
        $currentVer = $projXml.Project.PropertyGroup.Version
        $suffix = "-rc"
        $newVer = $currentVer + $suffix
        $projXml.Project.PropertyGroup.Version = $newVer
        $projXml.save("src\CommonHelpers.Maui\CommonHelpers.Maui.csproj")


    # ****** Restore and Build ***** #

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: NuGet Restore
      run: dotnet restore src/CommonHelpers.sln --runtime any

    - name: Build Projects
      run: |
        dotnet build src/CommonHelpers/CommonHelpers.csproj --configuration Release
        dotnet build src/CommonHelpers.Maui/CommonHelpers.Maui.csproj --configuration Release
        dotnet build src/CommonHelpers.Tests/CommonHelpers.Tests.csproj --configuration Release
    
    - name: Run Tests
      run: dotnet test src/CommonHelpers.Tests/CommonHelpers.Tests.csproj --runtime any


    # ***** CommonHelpers.Maui - Package Path Identification ***** #

    - name: Get Maui Version From Project
      uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
      id: get-version-number
      with:
        proj-path: src/CommonHelpers.Maui/CommonHelpers.Maui.csproj

    - name: Verify Maui version
      run: echo version "${{ steps.get-version-number.outputs.package-version }}"

    - name: Get Maui Package File Path
      id: get-package-path
      run : |
        $currentDirectory = Get-Location
        $outputFolder = Join-Path -Path $currentDirectory -ChildPath "src/CommonHelpers.Maui/bin/Release/"
        $match = Get-ChildItem $outputFolder -Recurse -Force -Include *.nupkg
        Write-Output "Setting output variable 'nuget-package-path' to $match"
        Write-Output "::set-output name=nuget-package-path::$match"

    - name: Verify Maui Package Path
      run: Write-Output Package path is "${{steps.get-package-path.outputs.nuget-package-path}}"


    # ***** NuGet Package Signing ***** #

    - name: Decode Base64 and save PFX file
      id: download-cert
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.LANCELOTSOFTWARECERT_BASE64 }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "LancelotSoftware.pfx"
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        Write-Output "Setting output variable 'certificate-path'..."
        Write-Output "::set-output name=certificate-path::$certificatePath"

    - name: Sign CommonHelpers.Maui NuGet package
      run: dotnet nuget sign ${{ steps.get-package-path.outputs.nuget-package-path }} --certificate-path ${{ steps.download-cert.outputs.certificate-path }} --certificate-password "${{ secrets.LANCELOTSOFTWARECERT_PASSWORD }}" --timestamper "http://timestamp.digicert.com"


    # Disabling nuget publishing until a solid need for prerelease packages on nuget.org exists

    # # ***** NuGet.org Release ***** #
    
    # - name: Publish CommonHelpers.Maui Prerelease to NuGet.org
    #   run: dotnet nuget push ${{ steps.get-package-path.outputs.nuget-package-path }} --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}


    # ***** GitHub Release ***** #

    - name: Create GitHub Prerelease
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v.${{ steps.get-version.outputs.package-version }}.${{ env.GITHUB_RUN_ID }}"
        release_name: "CommonHelpers.Maui ${{ steps.get-version.outputs.package-version }} (prerelease)"
        draft: false
        prerelease: true

    - name: Attach Maui Release Asset
      id: upload-sideload-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.get-package-path.outputs.nuget-package-path }}
        asset_name: "CommonHelpers.Maui.${{ steps.get-version-number.outputs.package-version }}.nupkg"
        asset_content_type: application/zip
