name: Prerelease

###############################################################
########################### WARNING ###########################
###############################################################
# Manual trigger only, this workflow publishes both to nuget.org!
on:
  workflow_dispatch:

permissions:
  contents: write  # Needed to create GitHub Releases
  id-token: write  # Needed for Azure auth (OIDC)

env:
  DOTNET_SDK_VERSION: '10.0.x'
  PROJ_PATH: 'src/CommonHelpers/CommonHelpers.csproj'
  PROJ_PATH_MAUI: 'src/CommonHelpers.Maui/CommonHelpers.Maui.csproj'

jobs:
  build:
    runs-on: windows-latest
    name: 'Build and Publish Prerelease'
    steps:
      # --------------- Setup --------------- #

    - name: Harden Runner
      uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
      with:
        egress-policy: audit

    - name: Azure login using OIDC via GitHub
      uses: azure/login@v3
      id: azlogin
      with:
        client-id: ${{vars.SERVICE_PRINCIPAL_CLIENT_ID}}
        tenant-id: ${{vars.SERVICE_PRINCIPAL_TENANT_ID}}
        subscription-id: ${{vars.SERVICE_PRINCIPAL_SUBSCRIPTION_ID}}

    - name: Checkout
      uses: actions/checkout@v6

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{env.DOTNET_SDK_VERSION}}

    - name: Install .NET Sign CLI tool
      run: dotnet tool install --tool-path . --prerelease sign

    - name: Install .NET Workload (maui)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v3

    # --------------- Work --------------- #

    - name: Add Release Candidate (-rc) suffix to Version Number
      run : |
        [xml]$projXml = get-content "src\CommonHelpers\CommonHelpers.csproj"
        $currentVer = $projXml.Project.PropertyGroup.Version
        $suffix = "-rc"
        $newVer = $currentVer + $suffix
        $projXml.Project.PropertyGroup.Version = $newVer
        $projXml.save("src\CommonHelpers\CommonHelpers.csproj")

    - name: Restore & Build CommonHelpers
      working-directory: src/CommonHelpers
      run: |
        dotnet restore --runtime any --ignore-failed-sources
        dotnet build --configuration Release

    - name: Add CommonHelpers Bin to NuGet Package Sources
      run: dotnet nuget add source "${{github.workspace}}\src\CommonHelpers\bin" --name "CommonHelpers_Bin"

    - name: Get Version From Project
      uses: kzrnm/get-net-sdk-project-versions-action@v2
      id: get-version
      with:
        proj-path: src/CommonHelpers/CommonHelpers.csproj

    - name: Get Package File Path
      id: get-package-path
      run : |
        $currentDirectory = Get-Location
        $outputFolder = Join-Path -Path $currentDirectory -ChildPath "src/CommonHelpers/bin/Release/"
        $match = Get-ChildItem $outputFolder -Recurse -Force -Include *.nupkg
        Write-Output "Setting output variable 'nuget-package-path' to $match"
        echo "nuget-package-path=$match" >> $env:GITHUB_OUTPUT

    - name: Restore & Build CommonHelpers.Maui
      working-directory: src/CommonHelpers.Maui
      run: |
        dotnet restore --runtime any --ignore-failed-sources
        dotnet build --configuration Release

    - name: Add CommonHelpers.Maui Bin to NuGet Package Sources
      run: dotnet nuget add source "${{github.workspace}}\src\CommonHelpers.Maui\bin" --name "CommonHelpers.Maui_Release"

    - name: Get Maui Version From Project
      uses: kzrnm/get-net-sdk-project-versions-action@v2
      id: get-version-maui
      with:
        proj-path: src/CommonHelpers.Maui/CommonHelpers.Maui.csproj

    - name: Get Maui Package File Path
      id: get-package-path-maui
      run : |
        $currentDirectory = Get-Location
        $outputFolder = Join-Path -Path $currentDirectory -ChildPath "src/CommonHelpers.Maui/bin/Release/"
        $match = Get-ChildItem $outputFolder -Recurse -Force -Include *.nupkg
        Write-Output "Setting output variable 'nuget-package-path-maui' to $match"
        echo "nuget-package-path-maui=$match" >> $env:GITHUB_OUTPUT

    - name: Restore & Build CommonHelpers.Tests
      working-directory: src/CommonHelpers.Tests
      run: |
        dotnet restore --runtime any --ignore-failed-sources
        dotnet build --configuration Release

    - name: Run Tests
      working-directory: src/CommonHelpers.Tests
      run: dotnet test --runtime any -c Release --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

    - name: Sign MSIX bundle
      uses: azure/trusted-signing-action@v2.0.0
      with:
        endpoint: ${{vars.SIGNING_ACCT_ENDPOINT_URL}}
        signing-account-name: ${{vars.SIGNING_ACCT_NAME}}
        certificate-profile-name: ${{vars.SIGNING_ACCT_CERT_PROFILE}}
        timestamp-rfc3161: http://timestamp.acs.microsoft.com
        timestamp-digest: SHA256
        file-digest: SHA256
        files: |
          ${{steps.get-package-path-maui.outputs.nuget-package-path-maui}}
          ${{steps.get-package-path.outputs.nuget-package-path}}
        exclude-azure-cli-credential: false
        exclude-environment-credential: true
        exclude-workload-identity-credential: true
        exclude-managed-identity-credential: true
        exclude-shared-token-cache-credential: true
        exclude-visual-studio-credential: true
        exclude-visual-studio-code-credential: true
        exclude-azure-powershell-credential: true
        exclude-azure-developer-cli-credential: true
        exclude-interactive-browser-credential: true

    - name: Upload CommonHelpers NuGet package artifact
      uses: actions/upload-artifact@v7
      with:
        name: "CommonHelpers.${{steps.get-version.outputs.package-version}}.nupkg"
        path: ${{steps.get-package-path.outputs.nuget-package-path}}

    - name: Upload CommonHelpers.Maui NuGet package artifact
      uses: actions/upload-artifact@v7
      with:
        name: "CommonHelpers.Maui.${{steps.get-version-maui.outputs.package-version}}.nupkg"
        path: ${{steps.get-package-path-maui.outputs.nuget-package-path-maui}}

    - name: Generate version number with date and workflow Run Number
      id: version-creator
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $runNumber = "$env:GITHUB_RUN_NUMBER"
        $ver = $buildDay + "." + $runNumber + ".0"
        echo "DATED_VERSION_NUM=$ver" >> $env:GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v3.0.0
      with:
        tag_name: "v${{steps.get-version.outputs.package-version}}"
        name: "CommonHelpers Preview ${{steps.get-version.outputs.package-version}}"
        draft: false
        prerelease: true
        files: |
          ${{steps.get-package-path.outputs.nuget-package-path}}
          ${{steps.get-package-path-maui.outputs.nuget-package-path-maui}}