name: Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest
    env:
      Actions_Allow_Unsecure_Commands: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Get Version From Project
      uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: src/CommonHelpers/CommonHelpers.csproj

    - name: Verify version
      run: echo version "${{steps.get-version.outputs.package-version}}"

    - name: NuGet Restore
      run: dotnet restore src/CommonHelpers.sln --configfile src/nuget.config --runtime any

    - name: Build
      run: dotnet build src/CommonHelpers.sln --configuration Release

    - name: Run Tests
      run: dotnet test src/CommonHelpers.sln --runtime any

    - name: Decode Base64 and save PFX file
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.LancelotSoftwareCert_Base64 }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "src\CommonHelpers\LancelotSoftware.pfx"
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        
    - name: Rename NuGet Package file(s) with '-rc' Release Candidatde suffix
      run : |
        $currentDirectory = Get-Location
        $packageFilePath = Join-Path -Path $currentDirectory -ChildPath "src/CommonHelpers/bin/Release/CommonHelpers.${{ steps.get-version.outputs.package-version }}.nupkg"
		echo "NUGET_PACKAGE_PATH=$packageFilePath" >> $GITHUB_ENV

    - name: Sign NuGet package
      run: dotnet nuget sign "**\CommonHelpers\bin\Release\CommonHelpers.${{ steps.get-version.outputs.package-version }}.nupkg" --certificate-path "src\CommonHelpers\LancelotSoftware.pfx" --certificate-password "${{ secrets.CertSigningPassword }}"
    
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v.${{ steps.get-version.outputs.package-version }} ${{  env.GITHUB_RUN_ID }}"
        release_name: "Prelease ${{ steps.get-version.outputs.package-version }}"
        draft: false
        prerelease: false

    - name: Publish preview
      id: upload-sideload-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "**/CommonHelpers.${{ steps.get-version.outputs.package-version }}.nupkg"
        asset_name: "CommonHelpers.${{ steps.get-version.outputs.package-version }}.nupkg"
        asset_content_type: application/zip

    - name: Publish Package to NuGet.org
      run: dotnet nuget push "D:\a\CommonHelpers\src\CommonHelpers\bin\Release\CommonHelpers.${{ steps.get-version.outputs.package-version }}.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
