name: Release to NuGet.org

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest
    env:
      Actions_Allow_Unsecure_Commands: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3

    - uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: src/CommonHelpers/CommonHelpers.csproj

    - run: |
        echo version "${{steps.get-version.outputs.version}}"
        echo version-prefix "${{steps.get-version.outputs.version-prefix}}" 
        echo version-suffix "${{steps.get-version.outputs.version-suffix}}" 
        echo package-version "${{steps.get-version.outputs.package-version}}" 
        echo assembly-version "${{steps.get-version.outputs.assembly-version}}" 
        echo file-version "${{steps.get-version.outputs.file-version}}" 
        echo informational-version "${{steps.get-version.outputs.informational-version}}"

    - name: NuGet Restore
      run: dotnet restore src/CommonHelpers.sln --configfile src/nuget.config --runtime any

    - name: Build
      run: dotnet restore src/CommonHelpers.sln --runtime any

    - name: run Tests
      run: dotnet test src/CommonHelpers.sln --runtime any

    - name: Publish Package to NuGet.org
      run: dotnet nuget push "bin/Release/CommonHelpers.${{ steps.get-version.outputs.version }}.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

    # https://github.com/marketplace/actions/publish-nuget
    # - name: publish on version change
    #   id: publish_nuget
    #   uses: rohith/publish-nuget@v2
    #   with:
    #     PROJECT_FILE_PATH: src/CommonHelpers/CommonHelpers.csproj
    #     PACKAGE_NAME: CommonHelpers
    #     NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
    #     NUGET_SOURCE: https://nuget.pkg.github.com/LanceMcCarthy/
    #     VERSION_STATIC: ${{ env:NBGV_SimpleVersion }}
