name: Release to GitHub Packages

on:
  push:
    branches:
      - prerelease

jobs:
  build:
    runs-on: windows-latest
    env:
      Actions_Allow_Unsecure_Commands: true 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    
    - name: Nerdbank.GitVersioning
      id: nbgv
      uses: dotnet/nbgv@v0.3.1
      with:
        path: src/CommonHelpers/
        setAllvars: true
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: NuGet Restore
      run: dotnet restore src/CommonHelpers.sln --runtime any

    - name: Build
      run: dotnet restore src/CommonHelpers.sln --runtime any

    - name: run Tests
      run: dotnet test src/CommonHelpers.sln --runtime any

      # Publishing NuGet package. Note this nuget.config is proving the authentication
    - name: Publish Package to GitHub Registry
      run: dotnet nuget push "bin/Release/CommonHelpers.${{ steps.nbgv.outputs.SimpleVersion }}.nupkg" --source "GitHubRegistry" --api-key ${{ secrets.GITHUB_TOKEN }}
