name: Release to NuGet.org

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest
    env:
      Actions_Allow_Unsecure_Commands: true 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.8,16.9)'

    - name: NuGet Restore
      run: dotnet restore src/CommonHelpers.sln --configfile src/nuget.config --runtime any

    - name: Build
      run: dotnet restore src/CommonHelpers.sln --runtime any

    - name: run Tests
      run: dotnet test src/CommonHelpers.sln --runtime any

    - name: Nerdbank.GitVersioning
      id: nbgv
      uses: dotnet/nbgv@v0.3.1
      with:
        path: src/CommonHelpers/CommonHelpers.csproj
        setAllvars: true

    - run: |
        echo "Environment vars"
        echo "NBGV_SemVer2 $env:NBGV_SemVer2"
        echo "NBGV_SimpleVersion $env:NBGV_SimpleVersion"
        echo "NBGV_VersionMajor $env:NBGV_VersionMajor"
        echo "NBGV_VersionMinor $env:NBGV_VersionMinor"
        echo "NBGV_BuildNumber $env:NBGV_BuildNumber"
        echo "NBGV_VersionRevision $env:NBGV_VersionRevision"

        echo "step output"
        echo "NBGV_SemVer2 ${{ steps.nbgv.outputs.SemVer2 }}"
        echo "NBGV_SimpleVersion ${{ steps.nbgv.outputs.SimpleVersion }}"
        echo "NBGV_VersionMajor ${{ steps.nbgv.outputs.VersionMajor }}"
        echo "NBGV_VersionMinor ${{ steps.nbgv.outputs.VersionMinor }}"
        echo "NBGV_BuildNumber ${{ steps.nbgv.outputs.BuildNumber }}"
        echo "NBGV_VersionRevision ${{ steps.nbgv.outputs.VersionRevision }}"

    - name: Publish Package to NuGet.org
      run: dotnet nuget push "bin/Release/CommonHelpers.${{ steps.nbgv.outputs.SimpleVersion }}.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

    # https://github.com/marketplace/actions/publish-nuget
    # - name: publish on version change
    #   id: publish_nuget
    #   uses: rohith/publish-nuget@v2
    #   with:
    #     PROJECT_FILE_PATH: src/CommonHelpers/CommonHelpers.csproj
    #     PACKAGE_NAME: CommonHelpers
    #     NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
    #     NUGET_SOURCE: https://nuget.pkg.github.com/LanceMcCarthy/
    #     VERSION_STATIC: ${{ env:NBGV_SimpleVersion }}
