name: Development

on:
  workflow_dispatch:
  push:
    branches:
      - 'issues/*'
      - 'features/*'
    paths:
      - 'src/**/*'
      - '.github/workflows/ci_dev.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.2

    # CommonHelpers project

    - name: Restore & Build CommonHelpers
      run: |
        dotnet restore src/CommonHelpers/CommonHelpers.csproj  --runtime any --ignore-failed-sources
        dotnet build src/CommonHelpers/CommonHelpers.csproj --configuration Release --no-restore

    - name: Add CommonHelpers Bin to NuGet Package Sources
      run: dotnet nuget add source "${{github.workspace}}\src\CommonHelpers\bin" --name "CommonHelpers_Bin"

    # CommonHelpers.Maui project

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore & Build CommonHelpers.Maui
      run: |
        dotnet restore src/CommonHelpers.Maui/CommonHelpers.Maui.csproj --runtime any --ignore-failed-sources
        dotnet build src/CommonHelpers.Maui/CommonHelpers.Maui.csproj --no-restore --configuration Release

    - name: Add CommonHelpers.Maui Bin to NuGet Package Sources
      run: dotnet nuget add source "${{github.workspace}}\src\CommonHelpers.Maui\bin" --name "CommonHelpers.Maui_Release"

    # CommonHelpers.Tests project

    - name: Restore & Build CommonHelpers.Tests
      run: |
        dotnet restore src/CommonHelpers.Tests/CommonHelpers.Tests.csproj --runtime any --ignore-failed-sources
        dotnet build src/CommonHelpers.Tests/CommonHelpers.Tests.csproj --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test src/CommonHelpers.Tests/CommonHelpers.Tests.csproj --runtime any -c Release --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
