name: Development

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'src/**/*'
      - '.github/workflows/ci_dev.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore Dependencies
      run: dotnet restore src/CommonHelpers.sln --runtime any --ignore-failed-sources

    - name: Build Projects
      run: |
        dotnet build src/CommonHelpers/CommonHelpers.csproj --configuration Release
        dotnet build src/CommonHelpers.Maui/CommonHelpers.Maui.csproj --configuration Release
        dotnet build src/CommonHelpers.Tests/CommonHelpers.Tests.csproj --configuration Release

    - name: Run Tests
      run: dotnet test src/CommonHelpers.Tests/CommonHelpers.Tests.csproj --runtime any
