name: Development

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest
    env:
      Actions_Allow_Unsecure_Commands: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Get Version From Project
      uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: src/CommonHelpers/CommonHelpers.csproj

    - name: Restore Dependencies
      run: dotnet restore src/CommonHelpers.sln --runtime any

    - name: Build CommonHelpers.sln
      run: dotnet build src/CommonHelpers.sln --configuration debug

    - name: Run Tests
      run: dotnet test src/CommonHelpers.sln --runtime any
