name: Development

on:
  workflow_dispatch:
  push:
    branches:
      - 'issues/*
      - 'features/*
    paths:
      - 'src/**/*'
      - '.github/workflows/ci_dev.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore & Build CommonHelpers
      run: |
        dotnet restore src/CommonHelpers/CommonHelpers.csproj  --runtime any --ignore-failed-sources
        dotnet build src/CommonHelpers/CommonHelpers.csproj --configuration Release

    - name: Restore & Build CommonHelpers.Maui
      run: |
        dotnet restore src/CommonHelpers.Maui/CommonHelpers.Maui.csproj --runtime any --ignore-failed-sources
        dotnet build src/CommonHelpers.Maui/CommonHelpers.Maui.csproj --configuration Release

    - name: Restore & Build CommonHelpers.Tests
      run: |
        dotnet restore src/CommonHelpers.Tests/CommonHelpers.Tests.csproj --runtime any --ignore-failed-sources
        dotnet build src/CommonHelpers.Tests/CommonHelpers.Tests.csproj --configuration Release

    - name: Run Tests
      run: dotnet test src/CommonHelpers.Tests/CommonHelpers.Tests.csproj --runtime any
