name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    # env:
    #   Actions_Allow_Unsecure_Commands: true 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Nerdbank.GitVersioning
      id: nbgv
      uses: dotnet/nbgv@v0.3.1
      with:
        path: src/CommonHelpers/CommonHelpers.csproj

    - run: |
        echo "Check Nerdbank.GitVersioning step output"
        echo "SemVer2 ${{ steps.nbgv.outputs.SemVer2 }}"
        echo "SimpleVersion ${{ steps.nbgv.outputs.SimpleVersion }}"
        echo "VersionMajor ${{ steps.nbgv.outputs.VersionMajor }}"
        echo "VersionMinor ${{ steps.nbgv.outputs.VersionMinor }}"
        echo "BuildNumber ${{ steps.nbgv.outputs.BuildNumber }}"
        echo "VersionRevision ${{ steps.nbgv.outputs.VersionRevision }}"
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.8,16.9)'

    - name: Restore Dependencies
      run: dotnet restore src/CommonHelpers.sln --configfile src/nuget.config --runtime any

    - name: Build CommonHelpers.sln
      run: dotnet restore src/CommonHelpers.sln --runtime any

    - name: Run Tests
      run: dotnet test src/CommonHelpers.sln --runtime any
