name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Add Alpha (-alpha) suffix to Version Number
      run : |
        [xml]$projXml = get-content "src\CommonHelpers\CommonHelpers.csproj"
        Write-Output "Before: " $projXml.Project.PropertyGroup.Version
        $currentVer = $projXml.Project.PropertyGroup.Version
        $suffix = "-alpha"
        $newVer = $currentVer + $suffix
        $projXml.Project.PropertyGroup.Version = $newVer
        Write-Output "After: " $projXml.Project.PropertyGroup.Version
        $projXml.save("src\CommonHelpers\CommonHelpers.csproj")

    - name: Install MAUI workloads (required for GitHub-hosted runners)
      shell: pwsh
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json

    - name: Restore Dependencies
      run: dotnet restore src/CommonHelpers.sln --runtime any

    - name: Build CommonHelpers.sln
      run: dotnet build src/CommonHelpers.sln --configuration Release

    - name: Run Tests
      run: dotnet test src/CommonHelpers.sln --runtime any


    # ***** Package Path Identification ***** #

    - name: Get Version From Project
      uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
      id: get-version
      with:
        proj-path: src/CommonHelpers/CommonHelpers.csproj

    - name: Verify version
      run: echo version "${{ steps.get-version.outputs.package-version }}"

    - name: Get Package File Path
      id: get-package-path
      run : |
        $currentDirectory = Get-Location
        $outputFolder = Join-Path -Path $currentDirectory -ChildPath "src/CommonHelpers/bin/Release/"
        $match = Get-ChildItem $outputFolder -Recurse -Force -Include *.nupkg
        Write-Output "Setting output variable 'nuget-package-path' to $match"
        Write-Output "::set-output name=nuget-package-path::$match"

    - name: Verify Package Path
      run: Write-Output Package path is "${{steps.get-package-path.outputs.nuget-package-path}}"


    # ***** Package Signing ***** #

    - name: Decode Base64 and save PFX file
      id: download-cert
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.LANCELOTSOFTWARECERT_BASE64 }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "LancelotSoftware.pfx"
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
        Write-Output "Setting output variable 'certificate-path'..."
        Write-Output "::set-output name=certificate-path::$certificatePath"

    - name: Sign NuGet package
      run: dotnet nuget sign ${{ steps.get-package-path.outputs.nuget-package-path }} --certificate-path ${{ steps.download-cert.outputs.certificate-path }} --certificate-password "${{ secrets.LANCELOTSOFTWARECERT_PASSWORD }}" --timestamper "http://timestamp.digicert.com"
