name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      Actions_Allow_Unsecure_Commands: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Get Version From Project
      uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: src/CommonHelpers/CommonHelpers.csproj

    - name: Echo version numbers
      run: |
        echo version "${{steps.get-version.outputs.version}}"
        echo version-prefix "${{steps.get-version.outputs.version-prefix}}" 
        echo version-suffix "${{steps.get-version.outputs.version-suffix}}" 
        echo package-version "${{steps.get-version.outputs.package-version}}" 
        echo assembly-version "${{steps.get-version.outputs.assembly-version}}" 
        echo file-version "${{steps.get-version.outputs.file-version}}" 
        echo informational-version "${{steps.get-version.outputs.informational-version}}"
    
    - name: Restore Dependencies
      run: dotnet restore src/CommonHelpers.sln --runtime any

    - name: Build CommonHelpers.sln
      run: dotnet restore src/CommonHelpers.sln --runtime any

    - name: Run Tests
      run: dotnet test src/CommonHelpers.sln --runtime any
    
    - name: Decode Base64 and save PFX file
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.LancelotSoftwareCert_Base64 }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "src\CommonHelpers\LancelotSoftware.pfx"
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Sign NuGet package
      run: dotnet nuget sign "src/CommonHelpers/bin/Release/CommonHelpers.${{ steps.get-version.outputs.package-version }}.nupkg" --certificate-path "src\CommonHelpers\LancelotSoftware.pfx" --certificate-password "${{ secrets.CertSigningPassword }}"
