name: Main [.NET MAUI]

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/CommonHelpers.Maui/**/*'
      - '.github/workflows/ci_main-maui.yml'

permissions:
  contents: read
  id-token: write  # Needed for Azure auth (OIDC)

env:
  DOTNET_SDK_VERSION: '10.0.x'
  PROJ_PATH: 'src/CommonHelpers/CommonHelpers.csproj'
  PROJ_PATH_MAUI: 'src/CommonHelpers.Maui/CommonHelpers.Maui.csproj'

jobs:
  build:
    runs-on: windows-latest
    name: 'CI - Main [.NET MAUI]'
    steps:
      # --------------- Setup --------------- #

    - name: Harden Runner
      uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
      with:
        egress-policy: audit

    - name: Azure login using OIDC via GitHub
      uses: azure/login@v3
      id: azlogin
      with:
        client-id: ${{vars.SERVICE_PRINCIPAL_CLIENT_ID}}
        tenant-id: ${{vars.SERVICE_PRINCIPAL_TENANT_ID}}
        subscription-id: ${{vars.SERVICE_PRINCIPAL_SUBSCRIPTION_ID}}

    - name: Checkout
      uses: actions/checkout@v6

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{env.DOTNET_SDK_VERSION}}

    - name: Install .NET Tool (Sign CLI)
      run: dotnet tool install --tool-path . --prerelease sign

    - name: Install .NET Workload (maui)
      run: dotnet workload install maui --source https://api.nuget.org/v3/index.json
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v3

    # --------------- Work --------------- #

    - name: Add Alpha (-alpha) suffix to Version Number
      run : |
        [xml]$projXml = get-content ${{env.PROJ_PATH}}
        Write-Output "Before: " $projXml.Project.PropertyGroup.Version
        $currentVer = $projXml.Project.PropertyGroup.Version
        $suffix = "-alpha"
        $newVer = $currentVer + $suffix
        $projXml.Project.PropertyGroup.Version = $newVer
        Write-Output "After: " $projXml.Project.PropertyGroup.Version
        $projXml.save(${{env.PROJ_PATH}})

    - name: Restore & Build CommonHelpers
      working-directory: src/CommonHelpers
      run: |
        dotnet restore --runtime any --ignore-failed-sources
        dotnet build --configuration Release

    - name: Add CommonHelpers Bin to NuGet Package Sources
      run: dotnet nuget add source "${{github.workspace}}\src\CommonHelpers\bin" --name "CommonHelpers_Bin"

    - name: Add CommonHelpers.Maui Bin to NuGet Package Sources
      run: dotnet nuget add source "${{github.workspace}}\src\CommonHelpers.Maui\bin" --name "CommonHelpers.Maui_Bin"

    - name: Get CommonHelpers.nupkg File Path
      id: get-package-path
      run : |
        $currentDirectory = Get-Location
        $outputFolder = Join-Path -Path $currentDirectory -ChildPath "src/CommonHelpers/bin/Release/"
        $match = Get-ChildItem $outputFolder -Recurse -Force -Include *.nupkg
        Write-Output "Setting output variable 'nuget-package-path' to $match"
        echo "nuget-package-path=$match" >> $env:GITHUB_OUTPUT

    - name: Add Alpha (-alpha) suffix to Maui Package Version Number
      run : |
        [xml]$projXml = get-content ${{env.PROJ_PATH_MAUI}}
        Write-Output "Before: " $projXml.Project.PropertyGroup.Version
        $currentVer = $projXml.Project.PropertyGroup.Version
        $suffix = "-alpha"
        $newVer = $currentVer + $suffix
        $projXml.Project.PropertyGroup.Version = $newVer
        Write-Output "After: " $projXml.Project.PropertyGroup.Version
        $projXml.save(${{env.PROJ_PATH_MAUI}})

    - name: Get Package Version From Project
      uses: kzrnm/get-net-sdk-project-versions-action@v2
      id: get-version
      with:
        proj-path: ${{env.PROJ_PATH}}

    - name: Get CommonHelpers.Maui Version From Project
      uses: kzrnm/get-net-sdk-project-versions-action@v3
      id: get-version-maui
      with:
        proj-path: ${{env.PROJ_PATH_MAUI}}

    - name: Restore & Build CommonHelpers.Maui
      working-directory: src/CommonHelpers.Maui
      run: |
        dotnet install "CommonHelpers" --version "${{steps.get-version.outputs.package-version}}"
        dotnet restore --runtime any --ignore-failed-sources
        dotnet build --configuration Release

    - name: Get CommonHelpers.Maui.nupkg File Path
      id: get-package-path-maui
      run : |
        $currentDirectory = Get-Location
        $outputFolder = Join-Path -Path $currentDirectory -ChildPath "src/CommonHelpers.Maui/bin/Release/"
        $match = Get-ChildItem $outputFolder -Recurse -Force -Include *.nupkg
        Write-Output "Setting output variable 'nuget-package-path-maui' to $match"
        echo "nuget-package-path-maui=$match" >> $env:GITHUB_OUTPUT

    - name: Restore & Build CommonHelpers.Tests
      working-directory: src/CommonHelpers.Tests
      run: |
        dotnet restore --runtime any --ignore-failed-sources
        dotnet build --configuration Release

    - name: Run Tests
      working-directory: src/CommonHelpers.Tests
      run: dotnet test --runtime any -c Release --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

    - name: Sign MSIX bundle
      uses: azure/trusted-signing-action@v2.0.0
      with:
        endpoint: ${{vars.SIGNING_ACCT_ENDPOINT_URL}}
        signing-account-name: ${{vars.SIGNING_ACCT_NAME}}
        certificate-profile-name: ${{vars.SIGNING_ACCT_CERT_PROFILE}}
        timestamp-rfc3161: http://timestamp.acs.microsoft.com
        timestamp-digest: SHA256
        file-digest: SHA256
        files: ${{steps.get-package-path-maui.outputs.nuget-package-path-maui}}
        exclude-azure-cli-credential: false
        exclude-environment-credential: true
        exclude-workload-identity-credential: true
        exclude-managed-identity-credential: true
        exclude-shared-token-cache-credential: true
        exclude-visual-studio-credential: true
        exclude-visual-studio-code-credential: true
        exclude-azure-powershell-credential: true
        exclude-azure-developer-cli-credential: true
        exclude-interactive-browser-credential: true

    - name: Upload CommonHelpers.Maui NuGet package artifact
      uses: actions/upload-artifact@v7
      with:
        name: "CommonHelpers.Maui.${{steps.get-version-maui.outputs.package-version}}.nupkg"
        path: ${{steps.get-package-path-maui.outputs.nuget-package-path-maui}}